apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro	
    desiredCapacity: 1
    ssh: 
       publicKeyName: sshkey1111

  - name: ng-2
    minSize: 1
    maxSize: 2 
    instancesDistribution:
       maxPrice: 0.02
       instanceTypes: ["t2.micro"] 
       onDemandBaseCapacity: 0
       onDemandPercentageAboveBaseCapacity: 60
       spotInstancePools: 1
    ssh: 
       publicKeyName: sshkey1111
